language: cpp
compiler: gcc
dist: trusty
before_script:
- echo $PWD
- wget http://downloads.sourceforge.net/project/urho3d/Urho3D/1.6/Urho3D-1.6-Linux-64bit-STATIC.tar.gz -O Urho3D.tar.gz
- tar -xvf Urho3D.tar.gz
- export URHO3D_HOME=$PWD/Urho3D-1.6-Linux-64bit-STATIC/usr/local
- echo $URHO3D_HOME
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
- mkdir build 
- cd build 
- echo $URHO3D_HOME
- cmake .. -DSTATES_ENGINE_ENABLE_TESTING=1 -DSTATES_ENGINE_LUA=1 -DTOLUA_DEBUG=1
- make 
- make test
after_failure:
- cd Testing
- cd Temporary
- cat CTestCostData.txt
- cat LastTest.txt
- cat LastTestsFailed.txt
- cd ..
- cd ..
- cd ..
- cd sources
- cd StatesEngine
- ls
- filesize = $(stat -c%s "tolua_AllStatesEngine.cpp")
- echo #filesize
- cat tolua_AllStatesEngine.cpp
