language: cpp
compiler: gcc
dist: trusty
sudo: required
before_script:
- echo $PWD
- wget http://downloads.sourceforge.net/project/urho3d/Urho3D/1.6/Urho3D-1.6-Linux-64bit-SHARED.tar.gz -O /tmp/Urho3D.tar.gz
- tar -xvf /tmp/Urho3D.tar.gz
- export URHO3D_HOME=$PWD/tmp/Urho3D/Urho3D-1.6-Linux-64bit-SHARED/usr/local
- echo $URHO3D_HOME
script:
- mkdir build 
- cd build 
- echo $URHO3D_HOME
- cmake .. -DSTATES_ENGINE_ENABLE_TESTING=1
- make 
- make test
